//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoOriginal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingRequest
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Time { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string Note { get; set; }
        public int Persons { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public string Telephone { get; set; }
        public int WaitingList { get; set; }
        public int BranchId { get; set; }
    
        public virtual BookingSchedule BookingSchedule { get; set; }
        public virtual Branch Branch { get; set; }
    }
}
