//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoOriginal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingSchedule
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Time { get; set; }
        public int EndTime { get; set; }
        public int BranchTableId { get; set; }
        public int BranchId { get; set; }
    
        public virtual BranchTable BranchTable { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual BookingRequest BookingRequest { get; set; }
    }
}
