//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoOriginal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BranchTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BranchTable()
        {
            this.BookingRequests = new HashSet<BookingRequest>();
        }

        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter table number")]
        [Display(Name = "Table Number")]
        public string TableNo { get; set; }

        [Required(ErrorMessage = "Please enter table capacity")]
        public int Capacity { get; set; }

        [Required(ErrorMessage = "Please enter branch")]
        [Display(Name = "Branch Name")]
        public int BranchId { get; set; }

        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingRequest> BookingRequests { get; set; }
    }
}
