//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoOriginal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Campaign
    {
        public int Id { get; set; }
        public string SendTo { get; set; }

        [Required(ErrorMessage = "Enter email subject")]
        public string Subject { get; set; }

        [Required(ErrorMessage = "Enter email content")]
        public string Content { get; set; }

        [Display(Name = "Sent Date")]
        public System.DateTime SendDate { get; set; }

        [DataType(DataType.Upload)]
        [Display(Name = "Attachment")]
        public string AttachmentPath { get; set; }
    }
}
