//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoOriginal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public int Menu { get; set; }
        public int Place { get; set; }
        public int Service { get; set; }
        public int BookingProcess { get; set; }
        public string Comment { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public int BranchId { get; set; }
        public int BookingRequestId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual BookingRequest BookingRequest { get; set; }
    }
}
